# Generated by Django 4.1.7 on 2023-04-05 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=50, verbose_name='Введите название датасета')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания датасета')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_of_time', models.DateField()),
                ('cars_count', models.IntegerField(max_length=5)),
                ('dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.datasets')),
            ],
        ),
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=50, verbose_name='Введите название дилера')),
                ('dealer_region', models.CharField(max_length=50, verbose_name='Введите регион дилера')),
                ('dealer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast', models.JSONField()),
                ('data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.datasetsdata')),
            ],
        ),
        migrations.AddField(
            model_name='datasets',
            name='dealer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.dealers'),
        ),
    ]
